const PDFDocument = require('pdfkit');

exports.createPdf = (content, data) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Header Title
    doc.fontSize(18).font('Helvetica-Bold').text('RTI Application Draft', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).font('Helvetica').text('Generated by RTI-Gen', { align: 'center' });
    doc.moveDown(2);

    // Divider Line
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown(2);

    // Meta Info
    doc.fontSize(10).font('Helvetica').fillColor('#555555');
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    if (data.department) {
        doc.text(`Department: ${data.department}`);
    }
    doc.moveDown(2);

    // Sanitize content (replace special chars that cause PDF issues with standard fonts)
    // Note: PDFKit's standard fonts only support WinAnsi encoding (Latin-1).
    // Hindi/Unicode characters will NOT render without a custom font.
    const sanitizedContent = content
        .replace(/['']/g, "'") // Smart quotes
        .replace(/[""]/g, '"') // Smart double quotes
        .replace(/–/g, "-")    // En-dash
        .replace(/—/g, "--")   // Em-dash
        .replace(/•/g, "*")    // Bullet
        .replace(/…/g, "...")  // Ellipsis
        .replace(/═/g, "=")    // Box drawing double horizontal
        .replace(/─/g, "-")    // Box drawing horizontal
        .replace(/│/g, "|")    // Box drawing vertical
        .replace(/[┌┐└┘┬┴├┤┼]/g, "+"); // Box drawing corners and junctions

    // Main Content
    doc.fontSize(12).font('Times-Roman').fillColor('black');

    // Split content by newlines to handle formatting
    const lines = sanitizedContent.split('\n');
    lines.forEach(line => {
        if (line.trim() === '') {
            doc.moveDown();
        } else {
            doc.text(line, {
                align: 'justify',
                indent: 0,
                paragraphGap: 5
            });
        }
    });

    // Footer
    const bottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc.text('', 50, doc.page.height - 50);
    doc.fontSize(8).fillColor('grey').text('This is a computer-generated draft. Please verify details before submission.', {
        align: 'center'
    });
    doc.page.margins.bottom = bottom;

    return doc;
};
